import bcrypt

def hashpw(password : str) -> bytes:
    """ Returns a hashed password"""

    return bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

def checkpw(password : str, hashed_password : bytes) -> bool:
    """ Returns True if hashed_password was generated by password"""

    return bcrypt.checkpw(password.encode('utf-8'), hashed_password)